# Generated by Django 5.1.5 on 2025-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='day_of_offer',
            field=models.IntegerField(),
        ),
    ]
