# Generated by Django 5.1.5 on 2025-01-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
